name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download latest SDL_shadercross artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v11
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repo: colinator27/SDL_shadercross
        check_artifacts: true
        name: SDL3_shadercross-VC-x64
        workflow: main.yml
    - name: Build shaders
      shell: cmd
      run: |
        7z x SDL3_shadercross-3.0.0-windows-VC-x64.zip
        set PATH=%PATH%;%cd%/SDL3_shadercross-3.0.0-windows-VC-x64/bin/
        cd ./shaders/src/
        compile.bat
        cd ../../
    - name: Build
      run: cargo build --release
    - name: Copy extra files
      shell: cmd
      run: |
        copy LICENSE "./target/release/LICENSE"
        copy README.md "./target/release/README.md"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dust-manipulator-win-x64
        path: |
          target/release/dust-manipulator.exe
          target/release/config.json
          target/release/assets/
          target/release/compiled_shaders/
          target/release/LICENSE
          target/release/README.md
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download latest SDL_shadercross artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v11
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repo: colinator27/SDL_shadercross
        check_artifacts: true
        name: SDL3_shadercross-linux-x64
        workflow: main.yml
    - name: Build shaders
      shell: bash
      run: |
        7z x SDL3_shadercross-3.0.0-linux-x64.tar.gz
        7z x SDL3_shadercross-3.0.0-linux-x64.tar
        export PATH=$PATH:${PWD}/SDL3_shadercross-3.0.0-linux-x64/bin/
        cd ./shaders/src/
        chmod +x compile.sh
        ./compile.sh
        cd ../../
    - name: Install additional SDL build dependencies
      shell: bash
      run: |
        sudo apt-get install build-essential git make \
        pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
        libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
        libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
        libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
        libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev \
        libwayland-dev libdecor-0-dev liburing-dev \
        libfreetype-dev
    - name: Build
      run: cargo build --release
    - name: Copy extra files
      shell: bash
      run: |
        cp LICENSE "./target/release/LICENSE"
        cp README.md "./target/release/README.md"
        rm "./target/release/config.json"
        cp config-for-linux.json "./target/release/config.json"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dust-manipulator-linux-x64
        path: |
          target/release/dust-manipulator
          target/release/config.json
          target/release/assets/
          target/release/compiled_shaders/
          target/release/LICENSE
          target/release/README.md
          
